defaults:
  - model: mlm

seed: ${trial_id}
trial_id: 0
project_name: guided_protein_seq

# provide this for comparing samples to gt
data_dir: /home/cemri/NOS/data
val_fn: val_iid.csv 

target_cols: ['ss_perc_sheet']
vocab_file: /home/cemri/NOS/vocab.txt

log_dir: "/home/cemri/NOS/scratch/logs/guided_protein_seq"
exp_name: test_sample
exp_dir: ${log_dir}/${exp_name}

ckpt_path: '/home/cemri/NOS/scratch/logs/guided_protein_seq/ar_mlm_test/models/best_by_valid/epoch-98-step-14157.ckpt'

max_epochs: 100 #to avoid errors

max_seq_len: 300
min_seq_len: 128
trim_strategy: "randomcrop"
vocab_size: 30

ngpu: 1

num_samples: 50
infill_seeds_fn: null

dps_enable: False

guidance_kwargs: null
# guidance_kwargs:
#   step_size: 0.1
#   stability_coef: 1e-2
#   num_steps: 2

hydra:
  run:
    dir: ${log_dir}
  sweep:
    dir: ${log_dir}
